# Generated by Django 4.0.4 on 2022-05-28 01:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=tinymce.models.HTMLField(default='new'),
            preserve_default=False,
        ),
    ]
